services:
  db:
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:5555:5432
    volumes:
      - "./docker/postgres:/var/lib/postgresql"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB:-badservers}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
